In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data=pd.read_csv('zomato.csv',encoding='latin-1')

In [3]:
data.head()

Restaurant ID         Restaurant Name  Country Code              City  \
0        6317637        Le Petit Souffle           162       Makati City   
1        6304287        Izakaya Kikufuji           162       Makati City   
2        6300002  Heat - Edsa Shangri-La           162  Mandaluyong City   
3        6318506                    Ooma           162  Mandaluyong City   
4        6314302             Sambo Kojin           162  Mandaluyong City   

                                             Address  \
0  Third Floor, Century City Mall, Kalayaan Avenu...   
1  Little Tokyo, 2277 Chino Roces Avenue, Legaspi...   
2  Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...   
3  Third Floor, Mega Fashion Hall, SM Megamall, O...   
4  Third Floor, Mega Atrium, SM Megamall, Ortigas...   

                                     Locality  \
0   Century City Mall, Poblacion, Makati City   
1  Little Tokyo, Legaspi Village, Makati City   
2  Edsa Shangri-La, Ortigas, Mandaluyong City   
3      SM Megamall, Ortigas, Mandaluyong City   
4      SM Megamall, Ortigas, Mandaluyong City   

                                    Locality Verbose   Longitude   Latitude  \
0  Century City Mall, Poblacion, Makati City, Mak...  121.027535  14.565443   
1  Little Tokyo, Legaspi Village, Makati City, Ma...  121.014101  14.553708   
2  Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...  121.056831  14.581404   
3  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.056475  14.585318   
4  SM Megamall, Ortigas, Mandaluyong City, Mandal...  121.057508  14.584450   

                           Cuisines  ...          Currency Has Table booking  \
0        French, Japanese, Desserts  ...  Botswana Pula(P)               Yes   
1                          Japanese  ...  Botswana Pula(P)               Yes   
2  Seafood, Asian, Filipino, Indian  ...  Botswana Pula(P)               Yes   
3                   Japanese, Sushi  ...  Botswana Pula(P)                No   
4                  Japanese, Korean  ...  Botswana Pula(P)               Yes   

  Has Online delivery Is delivering now Switch to order menu Price range  \
0                  No                No                   No           3   
1                  No                No                   No           3   
2                  No                No                   No           4   
3                  No                No                   No           4   
4                  No                No                   No           4   

   Aggregate rating  Rating color Rating text Votes  
0               4.8    Dark Green   Excellent   314  
1               4.5    Dark Green   Excellent   591  
2               4.4         Green   Very Good   270  
3               4.9    Dark Green   Excellent   365  
4               4.8    Dark Green   Excellent   229  

[5 rows x 21 columns]

In [4]:
data.shape

(9551, 21)

In [5]:
data.columns

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

In [6]:
data.drop(columns=['Restaurant ID','Is delivering now', 'Switch to order menu','Rating color', 'Rating text'],inplace=True)

In [7]:
data.columns

Index(['Restaurant Name', 'Country Code', 'City', 'Address', 'Locality',
       'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Price range', 'Aggregate rating', 'Votes'],
      dtype='object')

In [8]:
len(data['Restaurant Name'].value_counts())

7446

In [9]:
data=data[data['Country Code']==1]

In [10]:
data=data[data['City'].isin(['New Delhi','Gurgaon','Noida','Faridabad'])]

In [11]:
data.shape

(7922, 16)

In [12]:
data.drop(columns=['Restaurant Name', 'Country Code','Address','Locality','Locality Verbose','Currency' ],inplace=True)

In [13]:
data.columns

Index(['City', 'Longitude', 'Latitude', 'Cuisines', 'Average Cost for two',
       'Has Table booking', 'Has Online delivery', 'Price range',
       'Aggregate rating', 'Votes'],
      dtype='object')

In [14]:
data['Has Table booking'].replace({'Yes':1,'No':0},inplace=True)

In [15]:
data['Has Table booking'].value_counts()

0    6876
1    1046
Name: Has Table booking, dtype: int64

In [16]:
data['Has Online delivery'].replace({'Yes':1,'No':0},inplace=True)
data['Has Online delivery'].value_counts()

0    5609
1    2313
Name: Has Online delivery, dtype: int64

In [17]:
data.corr()['Average Cost for two']

Longitude               0.071752
Latitude                0.070993
Average Cost for two    1.000000
Has Table booking       0.642966
Has Online delivery     0.076953
Price range             0.847985
Aggregate rating        0.328440
Votes                   0.299089
Name: Average Cost for two, dtype: float64

In [18]:
data.drop(columns=['Has Online delivery','Price range'],inplace=True)

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7922 entries, 865 to 9112
Data columns (total 8 columns):
City                    7922 non-null object
Longitude               7922 non-null float64
Latitude                7922 non-null float64
Cuisines                7922 non-null object
Average Cost for two    7922 non-null int64
Has Table booking       7922 non-null int64
Aggregate rating        7922 non-null float64
Votes                   7922 non-null int64
dtypes: float64(3), int64(3), object(2)
memory usage: 557.0+ KB


In [20]:
data.head()

City  Longitude   Latitude                    Cuisines  \
865  Faridabad  77.306640  28.490059  Chinese, Fast Food, Bakery   
866  Faridabad  77.304776  28.490157       North Indian, Chinese   
867  Faridabad  77.305563  28.490137                North Indian   
868  Faridabad  77.306102  28.490098                North Indian   
869  Faridabad  77.305745  28.490062                      Bakery   

     Average Cost for two  Has Table booking  Aggregate rating  Votes  
865                   250                  0               2.9      4  
866                   500                  0               2.8     16  
867                   150                  0               2.8      8  
868                   150                  0               2.9      8  
869                   100                  0               2.8      7

In [21]:
a=data.groupby('Cuisines')['Average Cost for two'].mean().sort_values(ascending=False).reset_index()
data=data.merge(a,on="Cuisines")
data.drop(columns=['Cuisines'],inplace=True)


In [22]:
data.rename(columns={'Average Cost for two_x':'cost','Average Cost for two_y':'cuisine'},inplace=True)

In [23]:
y=data.iloc[:,3].values
y

array([ 250,  500,  500, ...,  450, 1000,  450], dtype=int64)

In [24]:
y.shape

(7922,)

In [25]:
X=data.drop(columns=['cost']).iloc[:,:].values
X

array([['Faridabad', 77.3066401, 28.4900591, ..., 2.9, 4, 375.0],
       ['New Delhi', 77.04952508, 28.80619877, ..., 0.0, 0, 375.0],
       ['Faridabad', 77.304776, 28.490156699999996, ..., 2.8, 16,
        594.3037974683544],
       ...,
       ['Noida', 77.3648332, 28.5971027, ..., 3.5, 105, 450.0],
       ['Noida', 77.32321292, 28.567750899999997, ..., 0.0, 0, 1000.0],
       ['Noida', 77.32530809999999, 28.5671503, ..., 2.0, 161, 450.0]],
      dtype=object)

In [26]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()

In [27]:
X[:,0]=encoder.fit_transform(X[:,0])

In [28]:
X[:,0]


array([0, 2, 0, ..., 3, 3, 3], dtype=object)

In [29]:
from sklearn.preprocessing import OneHotEncoder
oencoder=OneHotEncoder(categorical_features=[0])
X=oencoder.fit_transform(X).toarray()

C:\Users\CHANDRIMA\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\CHANDRIMA\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [30]:
X.shape

(7922, 10)

In [31]:
X[:,0:4]

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [32]:
X=X[:,1:]
X.shape

(7922, 9)

In [33]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=7)
from sklearn.linear_model import LinearRegression
regressor1= LinearRegression()

In [34]:
regressor1.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [35]:
y_pred=regressor1.predict(X_test)

In [36]:
y_pred.shape

(1585,)

In [37]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.6945487835658287